### ISSUE TITLE
demo运行问题

### ISSUE THREAD

**Issue by teorzhang** [xueyouluo/speller-bert#3]
请问大佬，demo网页点了检测按钮后为什么会报如下错误呢？
`ConnectionError: HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /predict (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001E174CA6470>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',))`

**Comment by xueyouluo** [comment]
你的模型serving有没有跑起来，另外端口号对不对

**Comment by teorzhang** [comment]
请问修改模型地址是在哪修改呢？还有我把demo.py和serving.py的地址和端口号都改为了localhost和8080

**Comment by xueyouluo** [comment]
模型地址在这边修改：https://github.com/xueyouluo/speller-bert/blob/main/cbert/serving.py#L32

启动serving.py后可以自己发个请求试试能否返回结果。

demo.py里面的调用模型端口要跟你serving的端口一致：https://github.com/xueyouluo/speller-bert/blob/main/cbert/serving.py#L32

不确定你把demo.py的端口改成8080会怎么样，但是它应该是你启动后自动给你找个合适的端口吧

**Comment by teorzhang** [comment]
那模型地址应该改成哪个模型文件呢？是像比如cbert/cbert.index吗？还是其他的文件路径？

**Comment by xueyouluo** [comment]
你解压后的文件目录比如为/home/XXX/data/cbert，那么模型路径就是/home/XXX/data/cbert/cbert，不要后面那个.index

**Comment by teorzhang** [comment]
是下载你文中提到的plome+finetune模型还是cbert模型（https://share.weiyun.com/wXErg7gB）呢？

**Comment by xueyouluo** [comment]
我分享的这个模型

**Comment by teorzhang** [comment]
请问报如下错误是为什么呢？
`2022-03-14 21:32:28.080084: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 1356 MB memory) -> physical GPU (device: 0, name: NVIDIA GeForce MX150, pci bus id: 0000:01:00.0, compute capability: 6.1)
2022-03-14 21:32:29.541374: W tensorflow/core/util/tensor_slice_reader.cc:95] Could not open D:\BaiduNetdiskDownload\cbert\cbert: Unknown: NewRandomAccessFile failed to Create/Open: D:\BaiduNetdiskDownload\cbert\cbert : �ܾ����ʡ�
; Input/output error
2022-03-14 21:32:29.545799: W tensorflow/core/util/tensor_slice_reader.cc:95] Could not open D:\BaiduNetdiskDownload\cbert\cbert: Unknown: NewRandomAccessFile failed to Create/Open: D:\BaiduNetdiskDownload\cbert\cbert : �ܾ����ʡ�
; Input/output error
2022-03-14 21:32:29.546449: W tensorflow/core/framework/op_kernel.cc:1651] OP_REQUIRES failed at save_restore_tensor.cc:175 : Data loss: Unable to open table file D:\BaiduNetdiskDownload\cbert\cbert: Unknown: NewRandomAccessFile failed to Create/Open: D:\BaiduNetdiskDownload\cbert\cbert : �ܾ����ʡ�
; Input/output error`

**Comment by teorzhang** [comment]
请问报如下错误是得到的jrequest.get_json（）出问题吗？还是进入check（）方法的时候出的问题？
`@app.route('/predict',methods=['POST'])

def predict():

  data = request.get_json(silent=True)

  print(data)         <--- 打印出来是(Ellipsis, Ellipsis)

  text = check(data['text'])            <-----报错TypeError: tuple indices must be integers or slices, not str

  return json.dumps({"text":text})`

**Comment by xueyouluo** [comment]
> 请问报如下错误是得到的jrequest.get_json（）出问题吗？还是进入check（）方法的时候出的问题？ `@app.route('/predict',methods=['POST'])
> 
> def predict():
> 
> data = request.get_json(silent=True)
> 
> print(data) <--- 打印出来是(Ellipsis, Ellipsis)
> 
> text = check(data['text']) <-----报错TypeError: tuple indices must be integers or slices, not str
> 
> return json.dumps({"text":text})`

你传入的数据有问题，正常应该是个dict比如， {'text':'我是测试'}。你启动serving后用requests测试一下
requests.post('http://localhost:8505/predict',json={"text":text}).json()

**Comment by teorzhang** [comment]
好像确实是requests.post('[http://localhost:8505/predict',json={"text":text}).json()这里出问题。启动serving.py后自己发个请求，是报500 Internal Server Error，但是不知道哪里出问题了。。。

**Comment by xueyouluo** [comment]
serving这边的报错内容发下看看

**Comment by teorzhang** [comment]
`D:\Anaconda3\envs\pytorchEnv\python.exe C:/Users/tao/Desktop/GP/speller-bert-main/cbert/serving.py
2022-03-15 18:10:02.850629: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
WARNING:tensorflow:
The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
  * https://github.com/tensorflow/io (for I/O related ops)
If you depend on functionality not listed there, please file an issue.

WARNING:tensorflow:From C:\Users\tao\Desktop\GP\speller-bert-main\cbert\modeling.py:745: dense (from tensorflow.python.layers.core) is deprecated and will be removed in a future version.
Instructions for updating:
Use keras.layers.Dense instead.
WARNING:tensorflow:From D:\Anaconda3\envs\pytorchEnv\lib\site-packages\tensorflow_core\python\layers\core.py:187: Layer.apply (from tensorflow.python.keras.engine.base_layer) is deprecated and will be removed in a future version.
Instructions for updating:
Please use `layer.__call__` method instead.
2022-03-15 18:10:11.620990: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
2022-03-15 18:10:11.627843: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library nvcuda.dll
2022-03-15 18:10:11.680177: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties: 
name: NVIDIA GeForce MX150 major: 6 minor: 1 memoryClockRate(GHz): 1.5315
pciBusID: 0000:01:00.0
2022-03-15 18:10:11.680614: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
2022-03-15 18:10:11.696365: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cublas64_100.dll
2022-03-15 18:10:11.710370: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cufft64_100.dll
2022-03-15 18:10:11.716693: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library curand64_100.dll
2022-03-15 18:10:11.736779: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusolver64_100.dll
2022-03-15 18:10:11.748151: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusparse64_100.dll
2022-03-15 18:10:11.782964: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudnn64_7.dll
2022-03-15 18:10:11.783324: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
2022-03-15 18:10:13.506014: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:
2022-03-15 18:10:13.506258: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]      0 
2022-03-15 18:10:13.506392: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 0:   N 
2022-03-15 18:10:13.507242: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 1356 MB memory) -> physical GPU (device: 0, name: NVIDIA GeForce MX150, pci bus id: 0000:01:00.0, compute capability: 6.1)
 * Running on http://localhost:8080/ (Press CTRL+C to quit)
(Ellipsis, Ellipsis)
[2022-03-15 18:10:54,495] ERROR in app: Exception on /predict [POST]
Traceback (most recent call last):
  File "D:\Anaconda3\envs\pytorchEnv\lib\site-packages\flask\app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\Anaconda3\envs\pytorchEnv\lib\site-packages\flask\app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\Anaconda3\envs\pytorchEnv\lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "D:\Anaconda3\envs\pytorchEnv\lib\site-packages\flask\app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "D:\Anaconda3\envs\pytorchEnv\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "D:\Anaconda3\envs\pytorchEnv\lib\site-packages\flask\app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\Anaconda3\envs\pytorchEnv\lib\site-packages\flask\app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:/Users/tao/Desktop/GP/speller-bert-main/cbert/serving.py", line 107, in predict
    text = check(data['text'])
TypeError: tuple indices must be integers or slices, not str
127.0.0.1 - - [15/Mar/2022 18:10:54] "POST /predict HTTP/1.1" 500 -
`

**Comment by xueyouluo** [comment]
TypeError: tuple indices must be integers or slices, not str

还是收到的数据不对。

text = check(data['text']) 这里可以改成 check('测试文本') 来看看模型能不能正常跑通，如果可以的话那就是请求的数据出了问题

**Comment by teorzhang** [comment]
改成check('测试文本')后模型可以跑通，确实是请求的数据有问题。我在想是不是因为requests和streamlit的版本有问题呢？我这两个都是安装的最高版本，想问您是哪个版本？

**Comment by xueyouluo** [comment]
requests = 2.25.1
streamlit = 1.2.0

**Comment by teorzhang** [comment]
还有请问您的flask版本是多少？

**Comment by xueyouluo** [comment]
flask = 2.0.3

**Comment by teorzhang** [comment]
感谢大佬！！我demo成功跑起来了，原来是各种库版本问题。另外想问一下cbert和bert有什么区别吗？去哪里能了解cbert模型呢？

**Comment by xueyouluo** [comment]
不客气。 cbert跟bert没什么太大的区别，全称应该较confusion bert，就是mask策略改成用了混淆字，而不是替换为[MASK]，你可以看看源码里面的实现，或者看一下PLOME那篇论文的介绍，我这里实现的cbert思路基本就是他里面介绍的cbert。

**Comment by teorzhang** [comment]
好的，感谢回复。

**Comment by teorzhang** [comment]
大佬，请问一下predict.py中的eval_inner_dataset()里的jsonl格式数据集是怎么得到的呢？例如corpus500.jsonl.jsonl这样的，是需要自己将json格式的文件转换成jsonl格式的吗？看到好像是要这样格式的{"src": "XXXXX", "tgt": "XXXXX"}，这种一般有什么方法转换呢？

**Comment by xueyouluo** [comment]
转成jsonl很简单啊，假设你数据是个字典的列表
```python
data = [{src:xxx,tgt:yyy},{src:xxx,tgt:yyy}]
with open(xxx,'w') as f:
  for x in data:
    f.write(json.dumps(x,ensure_ascii=False) + '\n')
  
```

**Comment by xueyouluo** [comment]
如果你是说我的测试集是怎么来的，那一部分是pycorrector里面的，一部分就是sighan的，其他的是我们自己收集的

**Comment by teorzhang** [comment]
明白了，感谢回复

**Comment by teorzhang** [comment]
大佬 请问一下，先预训练cbert再finetune和直接拿cbert来finetune，这有什么区别呢？前者效果会更好吗？

**Comment by xueyouluo** [comment]
你是说PLOME的cbert直接finetune吗？效果我已经对比过了的。我自己预训练的cbert其实思路跟PLOME的差不多，只是可能细节语料不一样，二者差别不大其实。

**Comment by teorzhang** [comment]
好的 感谢回复

**Comment by teorzhang** [comment]
大佬 请问一下，预训练cbert需要什么样的数据集？我的DATA_DIR选的是dimsim_confusion.json，我预训练的时候会在 data.py, line 148,in generator  text = x['text'].lower() 中报错，是我的数据集格式不对吗？

**Comment by xueyouluo** [comment]
> 大佬 请问一下，预训练cbert需要什么样的数据集？我的DATA_DIR选的是dimsim_confusion.json，我预训练的时候会在 data.py, line 148,in generator text = x['text'].lower() 中报错，是我的数据集格式不对吗？

jsonl格式的数据，每行是一条数据，有个text字段，比如
```
{"text":"aaaaa"}
{"text":"bbbbb"}
```

dimsim_confusion.json是构建混淆集用到的数据文件，不是训练数据

**Comment by teorzhang** [comment]
原来如此 我理解错了，那这个训练数据是您文中提到的微信语料库+新闻预料吗？还有为什么要用lowe()方法呢 这个不是用中文训练吗？

**Comment by xueyouluo** [comment]
数据是的。lower可有可无，估计写顺手了 😁。

**Comment by teorzhang** [comment]
好的 感谢回复
